In [2]:
# f.	Buatlah array 2D berikut menggunakan numpy
import numpy as np
arr = [
    [4,4,5], 
    [7,6,4],
    [9,7,4],
    [6,3,7]
]
array_2d = np.array(arr)
print(array_2d)
print(type(array_2d))

[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]
<class 'numpy.ndarray'>


In [3]:
# g.	Buatlah array 3D berikut menggunakan numpy
import numpy as np
# arr = np.zeros((2, 3, 4))
arr = [
    [
        [7,8,5],
        [4,7,7],
        [7,1,9],
        [5,4,10]
    ],
    [
        [2,1,2],
        [9,8,5],
        [3,7,3],
        [4,9,9]        
    ],
    [
        [2,9,3],
        [2,4,8],
        [1,6,6],
        [8,1,3]
    ]
]
array_3d = np.array(arr)
print(array_3d)
print(type(array_3d))

[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]
<class 'numpy.ndarray'>


In [4]:
# d.	Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. kemudian tambahkan 
# angka 2 pada setiap bilangan di kolom genap array berikut.
import numpy as np
arr = [
    [1,8,8,2], #0
    [8,2,1,2], #1
    [10,1,4,7],
    [1,4,7,8],
    [8,2,3,4]
]
array = np.array(arr)
arrayBaru = np.array([(array[x]+2 if (x+1)%2 == 0 else array[x]+1 ) for x in range(len(array))])
print(arrayBaru)

[[ 2  9  9  3]
 [10  4  3  4]
 [11  2  5  8]
 [ 3  6  9 10]
 [ 9  3  4  5]]


In [26]:
# d.	Tambahkan angka 1 pada setiap bilangan di baris ganjil array berikut. kemudian tambahkan 
# angka 2 pada setiap bilangan di kolom genap array berikut.
arr = [
    [1,8,8,2],
    [8,2,1,2],
    [10,1,4,7],
    [1,4,7,8],
    [8,2,3,4]
]
array = []
for i in range(len(arr)):
    tampung = []
    for j in range(len(arr[i])):
        if (i+1)%2 == 0:
            tampung.append(arr[i][j]+2)
        else:
            tampung.append(arr[i][j]+1)
    array.append(tampung)
arrNumpy = np.array(array)
print(arrNumpy)

[[ 2  9  9  3]
 [10  4  3  4]
 [11  2  5  8]
 [ 3  6  9 10]
 [ 9  3  4  5]]


In [6]:
# e.	Baliklah sumbu z array 3D berikut
arr = [
    [
        [7,8,5],
        [4,7,7],
        [7,1,9],
        [5,4,10]
    ],
    [
        [2,1,2],
        [9,8,5],
        [3,7,3],
        [4,9,9]        
    ],
    [
        [2,9,3],
        [2,4,8],
        [1,6,6],
        [8,1,3]
    ]
]
array = np.array(arr[::-1])
print(array)

[[[ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]

 [[ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]]

 [[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]]]


In [7]:
# f.	Ubahlah array pada soal e menjadi array 2D berukuran 6 x 6 (hint : gunakan perintah reshape)
arr = [
    [
        [7,8,5],
        [4,7,7],
        [7,1,9],
        [5,4,10]
    ],
    [
        [2,1,2],
        [9,8,5],
        [3,7,3],
        [4,9,9]        
    ],
    [
        [2,9,3],
        [2,4,8],
        [1,6,6],
        [8,1,3]
    ]
]
arrNew = np.array(arr).reshape(6,6)
print(arrNew)

[[ 7  8  5  4  7  7]
 [ 7  1  9  5  4 10]
 [ 2  1  2  9  8  5]
 [ 3  7  3  4  9  9]
 [ 2  9  3  2  4  8]
 [ 1  6  6  8  1  3]]


In [13]:
# e.	Ubahlah matris kiri menjadi matriks sebelah kanan
arr = [
    [5,10,10,7],
    [7,8,4,10],
    [9,10,2,5],
    [1,8,9,3], 
    [6,10,5,2],
    [4,6,9,4]
]
a = 3
b = 5
arr_new = []
while a<=b:
    arr_new.append([arr[a][2],arr[a][3],arr[a][0],arr[a][1]]) #[1,8,9,3] ---> [9,3,1,8]
    a += 1
    if len(arr_new) == 3:
        a = 0
        b = 2
arrNumpy = np.array(arr_new)
print('array lama:\n', np.array(arr))
print('\narray baru:\n',arrNumpy)

array lama:
 [[ 5 10 10  7]
 [ 7  8  4 10]
 [ 9 10  2  5]
 [ 1  8  9  3]
 [ 6 10  5  2]
 [ 4  6  9  4]]

array baru:
 [[ 9  3  1  8]
 [ 5  2  6 10]
 [ 9  4  4  6]
 [10  7  5 10]
 [ 4 10  7  8]
 [ 2  5  9 10]]
